### ISSUE TITLE
Deployment in BSC? 

### ISSUE THREAD

**Issue by tbem** [fafrd/disperse-nft-contract#3]
Can you deploy this on BSC please?

**Comment by fafrd** [comment]
Sure

**Comment by fafrd** [comment]
Done, I have deployed this at address `0x4Dc10B9c07DC00A6af5F8441324B8429D1e2C043` for both mainnet and testnet

https://bscscan.com/address/0x4Dc10B9c07DC00A6af5F8441324B8429D1e2C043
https://testnet.bscscan.com/address/0x4dc10b9c07dc00a6af5f8441324b8429d1e2c043

**Comment by fafrd** [comment]
a04cb902a289ce162e1b17e0a7026641131a1098
